### ISSUE TITLE
Some General Feedback. 

### ISSUE THREAD

**Issue by dellis1972** [AristurtleDev/building-2d-games-with-monogame#1]
This is really great stuff 😄 

The only bit of feedback I have is about the content in the Hello World section. 
There is allot of content in there. Following chapters about the layout of the project only show the default Game1.cs code. Perhaps it would make sense to split out the addition of the basic snake game to a section which comes after the Hello World (which just runs up the basic app) and the chapters which explain the project structure etc?

Just some thoughts.

**Comment by AristurtleDev** [comment]
I've split the initial prototype code out which will be used in a later chapter and the hello world is just a simple hello world now. Thanks @dellis1972 

Going to close this as I've opened chapter specific feedback issue to help keep track of feedback.  Thanks again
