### ISSUE TITLE
Chapter 02: Getting Started

### ISSUE THREAD

**Issue by AristurtleDev** [AristurtleDev/building-2d-games-with-monogame#10]
# Chapter 02: Getting Started Feedback

Please use this issue to discuss feedback specific to [Chapter 02: Getting Started](https://github.com/AristurtleDev/building-2d-games-with-monogame/blob/main/documentation/02-getting-started.md)

## Feedback Guidelines
When providing feedback, please adhere to the following guidelines 

- Provide feedback relevant to the chapter as defined by the title of this issue.
- For typos and grammatical errors, please provide them as a list with the line number they occur on.  Do not separate them into individual feedback sections based on paragraphs
- Use `#` headers where appropriate.  Do not use them just to enlarge text
- When correcting grammar, please ensure it is an actual grammar correction and not a personal opinion on how something should be written.  
- Inline with the above, suggestions on wording something better is encouraged, but please bear in mind that this tutorial is meant for developers who are already have a base understanding of C# as defined in the Preface documentation, and the tutorial is focused on teaching game development with MonoGame and not teaching C# programming.

## Feedback Template
To make providing feedback easier, You can copy and paste the following template into your comment submission

```md
## Chapter Feedback
<!-- provide feedback here related to the overall chapter.  Suggestions such as missing information, better explanations of topics, or removal of irrelevant content. -->

## Typos
<!-- provide a list here containing the line number and the typo made with a suggested correction -->
```

**Comment by titanix** [comment]
Why is Command Prompt prefixed by an asterix the two times it appears in the text?

**Comment by stromkos** [comment]
A couple of typos:

>This approach offers several advantages

Missing colon   "advantages:"
 
>like Git for you game projects.

you**r**

----

Linux section needs a link to the download Linux instructions:  https://learn.microsoft.com/en-us/dotnet/core/install/linux for other OS. The current link is only for Ubuntu.

> enter the following commands

> enter the following command

Missing colons

The word following will cause the sentence to end in a colon.

>  The project will compile and run, displaying a screen similar to the following

----

The mgcb editor can be manually run from inside the project folder with the following commands:

```
dotnet restore
dotnet tool run mgcb-editor
```

Before I go too far with the manual alternatives; It may be better to create a separate section for the dot-net commands:

```
dotnet new list
dotnet new mgdesktopgl -o dir1
cd dir1
dotnet restore

dotnet clean
dotnet build
dotnet run

dotnet tool run mgcb-editor
```
---

>there is a log going on behind the scenes that the MonoGame

lot not log

> 3. A loop is entered

A loop **was** entered

The tense of the verbs must be consistent in a list. 

----

> The handle this, games implement a loop structure that runs continuously, first calling a method to update the game logic, and then a draw method to render the current frame, until it has been told to exit.

This sentence has consistency and wording issues.

Suggested edit
---

**To** handle this behavior, the framework implements a version of following loop that runs continuously:

 1. Update the game logic.
 2. Draw the graphics to the screen.
 3. Wait, if configured, for the timer or screen refresh interval to expire, 60 FPS or about 16.66667 ms,  by default.
 4. Repeat unless exiting.

---

I don't know if you want to tackle async platform loops here.  So "a version" allows flexibility while giving a valid overview.

---


> game applications work differently than a traditional desktop application like...

Windows programs are based on loops focusing around the system event message pump.

---

>You install the MonoGame project templates.

install**ed**


----

**Comment by AristurtleDev** [comment]
@titanix  @stromkos  Thanks for the feedback, I forgot to update this repository to mention that everything is now moved into a draft PR with the actual documentation repository at https://github.com/MonoGame/docs.monogame.github.io/pull/85

As each chapter is written, it is put as a PR in my fork at https://github.com/AristurtleDev/docs.monogame.github.io/tree/2d-tutorial-bounty where I post for feedback from community and final approval from MonoGame foundation before merging that chapter into the draft PR.  

Future feedback should be left in these places.  

Again i apologize for the confusion and lack of me updating this repository since moving to the new system.  I will have an update on the bounty issue in the MonGame repo soon to explain this
