### ISSUE TITLE
Overall Feedback

### ISSUE THREAD

**Issue by AristurtleDev** [AristurtleDev/building-2d-games-with-monogame#3]
# Overall Feedback
Please use this issue to discuss and offer feedback on the tutorial project as a whole. Things such as order of chapters, pacing, topics discussed etc.  To submit feedback for a specific chapter, please use the issue for that chapter.

## Feedback Guidelines
When providing feedback, please adhere to the following guidelines 

- Provide feedback relevant to the chapter as defined by the title of this issue.
- For typos and grammatical errors, please provide them as a list with the line number they occur on.  Do not separate them into individual feedback sections based on paragraphs
- Use `#` headers where appropriate.  Do not use them just to enlarge text
- When correcting grammar, please ensure it is an actual grammar correction and not a personal opinion on how something should be written.  
- Inline with the above, suggestions on wording something better is encouraged, but please bear in mind that this tutorial is meant for developers who are already have a base understanding of C# as defined in the Preface documentation, and the tutorial is focused on teaching game development with MonoGame and not teaching C# programming.

## Feedback Template
To make providing feedback easier, You can copy and paste the following template into your comment submission

```md
## Chapter Feedback
<!-- provide feedback here related to the overall chapter.  Suggestions such as missing information, better explanations of topics, or removal of irrelevant content. -->

## Typos
<!-- provide a list here containing the line number and the typo made with a suggested correction -->
```

**Comment by MrValentine7777** [comment]
Just apologising here for the monster edits I submitted.

**Comment by MrValentine7777** [comment]
Oh, and you need to add the issue for Chapter 3 feedback.

**Comment by AristurtleDev** [comment]
@MrValentine7777  Thanks for the feedback, I forgot to update this repository to mention that everything is now moved into a draft PR with the actual documentation repository at https://github.com/MonoGame/docs.monogame.github.io/pull/85

As each chapter is written, it is put as a PR in my fork at https://github.com/AristurtleDev/docs.monogame.github.io/tree/2d-tutorial-bounty where I post for feedback from community and final approval from MonoGame foundation before merging that chapter into the draft PR.  

Future feedback should be left in these places.  

Again i apologize for the confusion and lack of me updating this repository since moving to the new system.  I will have an update on the bounty issue in the MonGame repo soon to explain this
